In [1]:
import pandas as pd

df = pd.read_csv(r"C:\Users\wwwww\Desktop\movie-success-analysis\data\raw\imdb_top_1000.csv")
df.head()

,Poster_Link,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Overview,Meta_score,Director,Star1,Star2,Star3,Star4,No_of_Votes,Gross
0,https://m.media-amazon.com/images/M/MV5BMDFkYT...,The Shawshank Redemption,1994,A,142 min,Drama,9.3,Two imprisoned men bond over a number of years...,80.0,Frank Darabont,Tim Robbins,Morgan Freeman,Bob Gunton,William Sadler,2343110,"28,341,469"
1,https://m.media-amazon.com/images/M/MV5BM2MyNj...,The Godfather,1972,A,175 min,"Crime, Drama",9.2,An organized crime dynasty's aging patriarch t...,100.0,Francis Ford Coppola,Marlon Brando,Al Pacino,James Caan,Diane Keaton,1620367,"134,966,411"
2,https://m.media-amazon.com/images/M/MV5BMTMxNT...,The Dark Knight,2008,UA,152 min,"Action, Crime, Drama",9.0,When the menace known as the Joker wreaks havo...,84.0,Christopher Nolan,Christian Bale,Heath Ledger,Aaron Eckhart,Michael Caine,2303232,"534,858,444"
3,https://m.media-amazon.com/images/M/MV5BMWMwMG...,The Godfather: Part II,1974,A,202 min,"Crime, Drama",9.0,The early life and career of Vito Corleone in ...,90.0,Francis Ford Coppola,Al Pacino,Robert De Niro,Robert Duvall,Diane Keaton,1129952,"57,300,000"
4,https://m.media-amazon.com/images/M/MV5BMWU4N2...,12 Angry Men,1957,U,96 min,"Crime, Drama",9.0,A jury holdout attempts to prevent a miscarria...,96.0,Sidney Lumet,Henry Fonda,Lee J. Cobb,Martin Balsam,John Fiedler,689845,"4,360,000"

In [2]:
# Check shape and info
print(df.shape)
print(df.info())

# Check missing values
print(df.isnull().sum())

(1000, 16)
<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 16 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Poster_Link    1000 non-null   str
 1   Series_Title   1000 non-null   str
 2   Released_Year  1000 non-null   str
 3   Certificate    899 non-null    str
 4   Runtime        1000 non-null   str
 5   Genre          1000 non-null   str
 6   IMDB_Rating    1000 non-null   float64
 7   Overview       1000 non-null   str
 8   Meta_score     843 non-null    float64
 9   Director       1000 non-null   str
 10  Star1          1000 non-null   str
 11  Star2          1000 non-null   str
 12  Star3          1000 non-null   str
 13  Star4          1000 non-null   str
 14  No_of_Votes    1000 non-null   int64
 15  Gross          831 non-null    str
dtypes: float64(2), int64(1), str(13)
memory usage: 125.1 KB
None
Poster_Link        0
Series_Title       0
Released_Year      0
Certificate      101
Runtime            0
Genre              0
IMDB_Rating        0
Overview           0
Meta_score       157
Director           0
Star1              0
Star2              0
Star3              0
Star4              0
No_of_Votes        0
Gross            169
dtype: int64

In [5]:

# 1. Convert Released_Year to numeric (integers) for proper analysis
df['Released_Year'] = pd.to_numeric(df['Released_Year'], errors='coerce')

# 2. Split Genre into a list of genres for multi-label analysis
df['Genre'] = df['Genre'].str.split(', ')

# 3. Standardize Certificate: remove dashes, convert to uppercase
df['Certificate'] = df['Certificate'].str.replace('-', '', regex=False).str.upper()

# 4. Ensure Gross is numeric (remove $ or , if needed)
df['Gross'] = df['Gross'].replace('[\$,]', '', regex=True).astype(float)

# 5. Clean Director and Star names: strip extra spaces
for col in ['Director', 'Star1', 'Star2', 'Star3', 'Star4']:
    df[col] = df[col].str.strip()

# 6. Remove duplicate rows if any exist
df = df.drop_duplicates()

# 7. Final verification: check data types and first few rows
print(df.info())
print(df.head())

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 16 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Poster_Link    1000 non-null   str
 1   Series_Title   1000 non-null   str
 2   Released_Year  999 non-null    float64
 3   Certificate    899 non-null    str
 4   Runtime        1000 non-null   str
 5   Genre          0 non-null      object
 6   IMDB_Rating    1000 non-null   float64
 7   Overview       1000 non-null   str
 8   Meta_score     843 non-null    float64
 9   Director       1000 non-null   str
 10  Star1          1000 non-null   str
 11  Star2          1000 non-null   str
 12  Star3          1000 non-null   str
 13  Star4          1000 non-null   str
 14  No_of_Votes    1000 non-null   int64
 15  Gross          831 non-null    float64
dtypes: float64(4), int64(1), object(1), str(10)
memory usage: 125.1+ KB
None
                                         Poster_Link  \
0  https://m.media-amazon.com/images/M/MV5BMDFkYT...
1  https://m.media-amazon.com/images/M/MV5BM2MyNj...
2  https://m.media-amazon.com/images/M/MV5BMTMxNT...
3  https://m.media-amazon.com/images/M/MV5BMWMwMG...
4  https://m.media-amazon.com/images/M/MV5BMWU4N2...

               Series_Title  Released_Year Certificate  Runtime Genre  \
0  The Shawshank Redemption         1994.0           A  142 min   NaN
1             The Godfather         1972.0           A  175 min   NaN
2           The Dark Knight         2008.0          UA  152 min   NaN
3    The Godfather: Part II         1974.0           A  202 min   NaN
4              12 Angry Men         1957.0           U   96 min   NaN

   IMDB_Rating                                           Overview  Meta_score  \
0          9.3  Two imprisoned men bond over a number of years...        80.0
1          9.2  An organized crime dynasty's aging patriarch t...       100.0
2          9.0  When the menace known as the Joker wreaks havo...        84.0
3          9.0  The early life and career of Vito Corleone in ...        90.0
4          9.0  A jury holdout attempts to prevent a miscarria...        96.0

               Director           Star1           Star2          Star3  \
0        Frank Darabont     Tim Robbins  Morgan Freeman     Bob Gunton
1  Francis Ford Coppola   Marlon Brando       Al Pacino     James Caan
2     Christopher Nolan  Christian Bale    Heath Ledger  Aaron Eckhart
3  Francis Ford Coppola       Al Pacino  Robert De Niro  Robert Duvall
4          Sidney Lumet     Henry Fonda     Lee J. Cobb  Martin Balsam

            Star4  No_of_Votes        Gross
0  William Sadler      2343110   28341469.0
1    Diane Keaton      1620367  134966411.0
2   Michael Caine      2303232  534858444.0
3    Diane Keaton      1129952   57300000.0
4    John Fiedler       689845    4360000.0

<>:11: SyntaxWarning: "\$" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\$"? A raw string is also an option.
<>:11: SyntaxWarning: "\$" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\$"? A raw string is also an option.
C:\Users\wwwww\AppData\Local\Temp\ipykernel_13368\2097027897.py:11: SyntaxWarning: "\$" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\$"? A raw string is also an option.
  df['Gross'] = df['Gross'].replace('[\$,]', '', regex=True).astype(float)

In [8]:
#Released_Year: fill missing
df['Released_Year'] = df['Released_Year'].fillna(df['Released_Year'].median())

In [9]:
#remove $ sign & convert to float
df['Gross'] = df['Gross'].replace('[\$,]', '', regex=True).astype(float)

<>:2: SyntaxWarning: "\$" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\$"? A raw string is also an option.
<>:2: SyntaxWarning: "\$" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\$"? A raw string is also an option.
C:\Users\wwwww\AppData\Local\Temp\ipykernel_13368\923544350.py:2: SyntaxWarning: "\$" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\$"? A raw string is also an option.
  df['Gross'] = df['Gross'].replace('[\$,]', '', regex=True).astype(float)

In [10]:
#Drop unusable columns
df = df.drop(columns=['Genre'])

In [11]:
#Check for duplicates
df = df.drop_duplicates()

In [12]:
#Check the cleaned data
df.info()
df.head()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 15 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Poster_Link    1000 non-null   str
 1   Series_Title   1000 non-null   str
 2   Released_Year  1000 non-null   float64
 3   Certificate    899 non-null    str
 4   Runtime        1000 non-null   str
 5   IMDB_Rating    1000 non-null   float64
 6   Overview       1000 non-null   str
 7   Meta_score     843 non-null    float64
 8   Director       1000 non-null   str
 9   Star1          1000 non-null   str
 10  Star2          1000 non-null   str
 11  Star3          1000 non-null   str
 12  Star4          1000 non-null   str
 13  No_of_Votes    1000 non-null   int64
 14  Gross          831 non-null    float64
dtypes: float64(4), int64(1), str(10)
memory usage: 117.3 KB

,Poster_Link,Series_Title,Released_Year,Certificate,Runtime,IMDB_Rating,Overview,Meta_score,Director,Star1,Star2,Star3,Star4,No_of_Votes,Gross
0,https://m.media-amazon.com/images/M/MV5BMDFkYT...,The Shawshank Redemption,1994.0,A,142 min,9.3,Two imprisoned men bond over a number of years...,80.0,Frank Darabont,Tim Robbins,Morgan Freeman,Bob Gunton,William Sadler,2343110,28341469.0
1,https://m.media-amazon.com/images/M/MV5BM2MyNj...,The Godfather,1972.0,A,175 min,9.2,An organized crime dynasty's aging patriarch t...,100.0,Francis Ford Coppola,Marlon Brando,Al Pacino,James Caan,Diane Keaton,1620367,134966411.0
2,https://m.media-amazon.com/images/M/MV5BMTMxNT...,The Dark Knight,2008.0,UA,152 min,9.0,When the menace known as the Joker wreaks havo...,84.0,Christopher Nolan,Christian Bale,Heath Ledger,Aaron Eckhart,Michael Caine,2303232,534858444.0
3,https://m.media-amazon.com/images/M/MV5BMWMwMG...,The Godfather: Part II,1974.0,A,202 min,9.0,The early life and career of Vito Corleone in ...,90.0,Francis Ford Coppola,Al Pacino,Robert De Niro,Robert Duvall,Diane Keaton,1129952,57300000.0
4,https://m.media-amazon.com/images/M/MV5BMWU4N2...,12 Angry Men,1957.0,U,96 min,9.0,A jury holdout attempts to prevent a miscarria...,96.0,Sidney Lumet,Henry Fonda,Lee J. Cobb,Martin Balsam,John Fiedler,689845,4360000.0

In [18]:
df.to_csv("../data/cleaned/cleaned_movies.csv", index=False)